### ISSUE TITLE
Add support for type java media type param

### ISSUE THREAD

**Issue by jam01** [MS3Inc/datasonnet-mapper#15]
Reintroduce support for specifying the target class type with the Java media type. The parameter should be named type.

Seeing how we now have programmatic access to request a target class type the plugin needs to make sure that the type specified in the media type param is at least a subclass or superclass and use the most specific one when converting, otherwise throw an exception.

**Comment by fugu13** [comment]
This should be handled by my additions in my PR for merging all the MS3 changes
